<html>
<head>
	<meta charset="utf-8">
	<title>Welcome to Coupon</title>
	<meta name='viewport' 
     content='width=device-width, initial-scale=1.0, maximum-scale=1.0, 
     user-scalable=0' >
	
	<link rel="stylesheet" href="<?php echo base_url('/assets/css/style.css') ?>">
</head>

<body>
	<div class="grid">
		<div class="panel">
			<div class="logo">
				<img src="<?php echo base_url('/assets/images/logo.png') ?>" alt="Danfoss Logo">
			</div>

			<?php if($this->session->flashdata('error')){ ?>
				<div class="alert-danger">
					<?php echo $this->session->flashdata('error'); ?>
				</div>
			<?php } ?>


			<?php echo form_open('DF/verify') ?>
			<div class="enter">
				<div class="lable">
					Enter Coupon Code
				</div>
				<input type="text" name='coupon' class="form-feild">
			</div>
			<div class="terms">
				<div class="terms-content">
					<p><b>Terms and condition</b></p>
					Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque elit eget gravida cum sociis. Et leo duis ut diam quam nulla porttitor massa. Volutpat diam ut venenatis tellus in metus vulputate. Tristique senectus et netus et malesuada. Diam vel quam elementum pulvinar etiam non. Non tellus orci ac auctor augue mauris. Quis enim lobortis scelerisque fermentum. Sapien faucibus et molestie ac feugiat. Metus vulputate eu scelerisque felis imperdiet proin. Id ornare arcu odio ut sem nulla pharetra diam. Vulputate sapien nec sagittis aliquam malesuada bibendum arcu. Donec pretium vulputate sapien nec sagittis aliquam malesuada bibendum. Lorem ipsum dolor sit amet consectetur adipiscing elit duis. Vivamus at augue eget arcu dictum varius duis. Egestas congue quisque egestas diam.

					Quis auctor elit sed vulputate mi sit amet mauris commodo. Sit amet massa vitae tortor condimentum lacinia. Scelerisque felis imperdiet proin fermentum. Facilisis volutpat est velit egestas dui id ornare arcu odio. Rhoncus aenean vel elit scelerisque mauris. Eget aliquet nibh praesent tristique. Amet porttitor eget dolor morbi non arcu risus quis varius. Mollis aliquam ut porttitor leo. Odio aenean sed adipiscing diam donec adipiscing. Lacus vel facilisis volutpat est velit egestas dui. In arcu cursus euismod quis viverra nibh cras. Tristique senectus et netus et malesuada fames ac turpis. Phasellus faucibus scelerisque eleifend donec pretium vulputate sapien nec sagittis. Nec ultrices dui sapien eget mi. Egestas maecenas pharetra convallis posuere morbi leo urna molestie at. Facilisi etiam dignissim diam quis enim lobortis scelerisque fermentum.

					Enim lobortis scelerisque fermentum dui faucibus. Orci eu lobortis elementum nibh tellus molestie nunc non. Duis at tellus at urna condimentum mattis. Etiam sit amet nisl purus in. Lobortis scelerisque fermentum dui faucibus in ornare quam. Arcu cursus vitae congue mauris rhoncus. Tincidunt ornare massa eget egestas purus viverra accumsan. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. Vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Viverra justo nec ultrices dui. Fermentum iaculis eu non diam phasellus. Integer eget aliquet nibh praesent tristique magna. A cras semper auctor neque vitae tempus quam pellentesque. Donec enim diam vulputate ut pharetra. Consequat mauris nunc congue nisi vitae suscipit tellus mauris. Egestas pretium aenean pharetra magna ac. Tempus urna et pharetra pharetra massa massa ultricies mi. In arcu cursus euismod quis viverra nibh cras pulvinar.

					In cursus turpis massa tincidunt dui. At risus viverra adipiscing at in tellus integer. Malesuada fames ac turpis egestas. Iaculis at erat pellentesque adipiscing commodo elit at imperdiet. Commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Consectetur adipiscing elit pellentesque habitant morbi tristique senectus et netus. Morbi quis commodo odio aenean sed adipiscing diam donec. Sit amet nulla facilisi morbi tempus iaculis urna id volutpat. Cursus mattis molestie a iaculis at erat. Nunc sed id semper risus. Ipsum suspendisse ultrices gravida dictum fusce ut placerat orci nulla. Elit at imperdiet dui accumsan sit amet. Velit sed ullamcorper morbi tincidunt ornare massa.

					Fusce id velit ut tortor pretium viverra. Vestibulum morbi blandit cursus risus at ultrices mi tempus imperdiet. Quis lectus nulla at volutpat diam. Nulla malesuada pellentesque elit eget gravida cum sociis natoque penatibus. Suspendisse sed nisi lacus sed viverra tellus in. Mi ipsum faucibus vitae aliquet nec. Quisque egestas diam in arcu cursus euismod quis viverra. Eget sit amet tellus cras adipiscing enim. Enim facilisis gravida neque convallis a cras. Integer eget aliquet nibh praesent.

					Etiam non quam lacus suspendisse faucibus. A arcu cursus vitae congue. Semper auctor neque vitae tempus quam pellentesque. Mi quis hendrerit dolor magna eget est lorem ipsum dolor. Gravida quis blandit turpis cursus in. Morbi tincidunt augue interdum velit euismod in. Felis bibendum ut tristique et egestas quis ipsum. Fringilla est ullamcorper eget nulla facilisi etiam dignissim diam. Dolor morbi non arcu risus quis varius quam quisque id. Condimentum id venenatis a condimentum vitae sapien pellentesque habitant morbi. Integer enim neque volutpat ac tincidunt vitae semper quis. Sed vulputate odio ut enim blandit volutpat maecenas. Amet nisl suscipit adipiscing bibendum. Quis commodo odio aenean sed. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Elementum nisi quis eleifend quam adipiscing vitae proin sagittis nisl. Mauris in aliquam sem fringilla ut morbi tincidunt augue. Interdum consectetur libero id faucibus nisl tincidunt eget. Lorem ipsum dolor sit amet.

					Turpis massa sed elementum tempus egestas. Quis eleifend quam adipiscing vitae proin sagittis nisl rhoncus. Elementum facilisis leo vel fringilla est. Gravida arcu ac tortor dignissim convallis aenean et. Purus sit amet volutpat consequat mauris. Vel risus commodo viverra maecenas accumsan. Diam ut venenatis tellus in metus vulputate eu scelerisque. Tortor pretium viverra suspendisse potenti nullam. Condimentum mattis pellentesque id nibh tortor id. In fermentum et sollicitudin ac orci. Convallis posuere morbi leo urna molestie at. Sollicitudin nibh sit amet commodo nulla facilisi nullam. In fermentum posuere urna nec tincidunt praesent semper feugiat. Diam sollicitudin tempor id eu nisl.

					Turpis egestas integer eget aliquet nibh praesent tristique magna sit. Eu nisl nunc mi ipsum faucibus vitae aliquet. Ultrices dui sapien eget mi proin sed libero. Neque viverra justo nec ultrices dui sapien eget mi. Duis tristique sollicitudin nibh sit amet commodo nulla facilisi nullam. Sed cras ornare arcu dui vivamus. Ultrices mi tempus imperdiet nulla malesuada pellentesque. Massa tincidunt dui ut ornare lectus. Blandit aliquam etiam erat velit scelerisque in dictum non. Consequat ac felis donec et odio pellentesque. Id interdum velit laoreet id donec ultrices tincidunt arcu non. Tempor orci dapibus ultrices in iaculis nunc. Ornare aenean euismod elementum nisi quis eleifend. Bibendum ut tristique et egestas quis ipsum suspendisse.

					Cursus metus aliquam eleifend mi in nulla. Est ante in nibh mauris cursus mattis molestie a. Elit eget gravida cum sociis natoque penatibus. Sed viverra ipsum nunc aliquet bibendum enim facilisis. Vulputate enim nulla aliquet porttitor lacus luctus accumsan. Arcu dui vivamus arcu felis bibendum ut tristique et. Nibh cras pulvinar mattis nunc sed blandit libero volutpat. Vitae congue mauris rhoncus aenean vel. Turpis in eu mi bibendum neque egestas congue. Quam elementum pulvinar etiam non quam lacus suspendisse faucibus. Maecenas volutpat blandit aliquam etiam erat velit scelerisque.

					Mi in nulla posuere sollicitudin aliquam ultrices sagittis orci a. A diam maecenas sed enim ut. Nunc vel risus commodo viverra maecenas accumsan lacus. Nunc faucibus a pellentesque sit. Sed turpis tincidunt id aliquet risus feugiat in ante. Laoreet suspendisse interdum consectetur libero id faucibus nisl. Ut consequat semper viverra nam libero justo laoreet sit amet. Laoreet sit amet cursus sit amet dictum sit amet. At urna condimentum mattis pellentesque id nibh tortor. Euismod nisi porta lorem mollis aliquam ut porttitor. Egestas pretium aenean pharetra magna ac placerat vestibulum lectus. Id semper risus in hendrerit. Vitae aliquet nec ullamcorper sit amet risus nullam eget. Lectus sit amet est placerat in egestas erat imperdiet sed. Porttitor leo a diam sollicitudin tempor id.

					Blandit massa enim nec dui nunc mattis. Est ultricies integer quis auctor elit sed. Porta non pulvinar neque laoreet. Elementum pulvinar etiam non quam lacus suspendisse faucibus. Morbi tincidunt ornare massa eget egestas purus viverra. Tincidunt eget nullam non nisi est sit. Eget mauris pharetra et ultrices. Quis auctor elit sed vulputate mi. Vehicula ipsum a arcu cursus vitae. Id diam maecenas ultricies mi. Nibh nisl condimentum id venenatis a condimentum. Arcu non odio euismod lacinia.

					Id consectetur purus ut faucibus pulvinar elementum. Ultricies integer quis auctor elit sed vulputate. Purus semper eget duis at tellus at urna condimentum mattis. Mattis rhoncus urna neque viverra justo nec ultrices dui sapien. Viverra vitae congue eu consequat ac felis. Orci porta non pulvinar neque laoreet. Quis viverra nibh cras pulvinar mattis nunc. Diam ut venenatis tellus in metus vulputate eu. Tellus cras adipiscing enim eu turpis. Tempus egestas sed sed risus pretium.

					Amet mattis vulputate enim nulla aliquet porttitor lacus luctus. Porta nibh venenatis cras sed. Suspendisse faucibus interdum posuere lorem ipsum dolor sit. Leo a diam sollicitudin tempor. Neque egestas congue quisque egestas diam in arcu cursus. Odio eu feugiat pretium nibh ipsum consequat nisl. Duis at consectetur lorem donec massa sapien faucibus et molestie. Et malesuada fames ac turpis egestas integer eget aliquet nibh. Ornare aenean euismod elementum nisi quis eleifend quam adipiscing. Volutpat est velit egestas dui id ornare arcu odio. Sollicitudin tempor id eu nisl nunc mi ipsum. Ridiculus mus mauris vitae ultricies leo integer malesuada. Tortor pretium viverra suspendisse potenti nullam ac tortor. Sit amet aliquam id diam maecenas ultricies mi. Duis at tellus at urna condimentum mattis. A iaculis at erat pellentesque adipiscing commodo.

					Magna eget est lorem ipsum dolor. Condimentum id venenatis a condimentum vitae sapien. Venenatis a condimentum vitae sapien pellentesque habitant morbi tristique senectus. Ut venenatis tellus in metus. Pharetra convallis posuere morbi leo urna. Nunc sed blandit libero volutpat sed. Facilisi cras fermentum odio eu feugiat pretium nibh. Sagittis eu volutpat odio facilisis mauris sit amet massa. Tristique et egestas quis ipsum suspendisse ultrices gravida. Eget est lorem ipsum dolor sit amet consectetur adipiscing elit. Duis convallis convallis tellus id interdum velit. Maecenas volutpat blandit aliquam etiam erat.

					Ac orci phasellus egestas tellus rutrum tellus pellentesque eu. Et netus et malesuada fames ac turpis egestas. Fusce ut placerat orci nulla pellentesque dignissim. Quis ipsum suspendisse ultrices gravida dictum fusce ut placerat. Mus mauris vitae ultricies leo integer malesuada nunc. Ac turpis egestas sed tempus urna et pharetra pharetra. Risus feugiat in ante metus dictum at tempor. Ante in nibh mauris cursus. Scelerisque in dictum non consectetur. Nec tincidunt praesent semper feugiat nibh. Pellentesque habitant morbi tristique senectus et. Auctor eu augue ut lectus arcu bibendum at varius.

					Habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Quis hendrerit dolor magna eget est. Praesent elementum facilisis leo vel fringilla est ullamcorper eget nulla. Sit amet commodo nulla facilisi nullam. Duis convallis convallis tellus id interdum velit. Arcu non sodales neque sodales. Volutpat consequat mauris nunc congue. Diam in arcu cursus euismod quis viverra. Egestas quis ipsum suspendisse ultrices gravida dictum. Adipiscing vitae proin sagittis nisl. Quis risus sed vulputate odio ut enim blandit volutpat. Donec pretium vulputate sapien nec sagittis aliquam. Porttitor leo a diam sollicitudin tempor id. Vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt. Velit dignissim sodales ut eu sem integer vitae.

					Massa massa ultricies mi quis. Aenean et tortor at risus viverra adipiscing at in. Vitae proin sagittis nisl rhoncus mattis rhoncus urna neque viverra. Ultrices dui sapien eget mi proin sed libero enim. Ut faucibus pulvinar elementum integer enim. Donec et odio pellentesque diam volutpat commodo sed egestas. Mus mauris vitae ultricies leo integer malesuada nunc vel. Senectus et netus et malesuada fames ac turpis. Pharetra pharetra massa massa ultricies mi. Aliquam sem et tortor consequat id porta nibh venenatis cras. In hac habitasse platea dictumst vestibulum rhoncus est pellentesque. Nec sagittis aliquam malesuada bibendum arcu vitae elementum. Vulputate dignissim suspendisse in est ante. Neque vitae tempus quam pellentesque. Facilisi cras fermentum odio eu feugiat pretium nibh ipsum consequat. Volutpat blandit aliquam etiam erat velit scelerisque in.

					Tempor orci dapibus ultrices in. Cras fermentum odio eu feugiat pretium nibh. At quis risus sed vulputate odio ut enim. Ut tortor pretium viverra suspendisse potenti. Diam maecenas ultricies mi eget mauris pharetra et ultrices neque. Posuere ac ut consequat semper viverra nam. Ut faucibus pulvinar elementum integer enim neque volutpat ac. Cursus in hac habitasse platea dictumst quisque sagittis purus. Eget egestas purus viverra accumsan in nisl nisi. Amet nulla facilisi morbi tempus iaculis urna id volutpat.

					Urna nec tincidunt praesent semper feugiat nibh sed pulvinar proin. Aliquam eleifend mi in nulla posuere sollicitudin aliquam ultrices. Id semper risus in hendrerit gravida. Urna id volutpat lacus laoreet non curabitur. Nullam vehicula ipsum a arcu. Mi in nulla posuere sollicitudin aliquam ultrices sagittis orci. Imperdiet proin fermentum leo vel orci. Tincidunt vitae semper quis lectus nulla at volutpat diam ut. Mollis aliquam ut porttitor leo a diam sollicitudin tempor. Non curabitur gravida arcu ac tortor dignissim convallis aenean. Nam libero justo laoreet sit amet cursus sit amet dictum. Praesent semper feugiat nibh sed pulvinar proin gravida hendrerit. Interdum velit euismod in pellentesque massa placerat duis. Molestie ac feugiat sed lectus vestibulum. Ultrices eros in cursus turpis massa tincidunt dui.

					Diam quam nulla porttitor massa. Ultrices neque ornare aenean euismod elementum nisi. Aliquet eget sit amet tellus cras adipiscing enim. Eget duis at tellus at. Facilisis sed odio morbi quis. Curabitur gravida arcu ac tortor dignissim convallis aenean et. Nulla pellentesque dignissim enim sit amet venenatis urna. Vel pharetra vel turpis nunc eget lorem dolor. Sapien pellentesque habitant morbi tristique senectus et netus et. Ac odio tempor orci dapibus. In ornare quam viverra orci sagittis eu. Magnis dis parturient montes nascetur. Fringilla urna porttitor rhoncus dolor purus non enim praesent elementum. Eu feugiat pretium nibh ipsum consequat nisl vel. Ridiculus mus mauris vitae ultricies leo. Sapien pellentesque habitant morbi tristique.

					Duis convallis convallis tellus id interdum velit laoreet id donec. Nibh nisl condimentum id venenatis a condimentum vitae sapien pellentesque. Ut diam quam nulla porttitor massa. Ut diam quam nulla porttitor massa id neque. Bibendum est ultricies integer quis auctor. Sit amet commodo nulla facilisi nullam vehicula ipsum a arcu. Quisque non tellus orci ac auctor augue mauris. Mauris vitae ultricies leo integer malesuada. Faucibus scelerisque eleifend donec pretium vulputate sapien. Ullamcorper a lacus vestibulum sed. Dictum non consectetur a erat nam at lectus urna. Proin libero nunc consequat interdum varius sit amet mattis vulputate. Pellentesque habitant morbi tristique senectus et netus et. Ipsum dolor sit amet consectetur. Aliquam faucibus purus in massa tempor nec feugiat nisl. Et netus et malesuada fames. Vitae aliquet nec ullamcorper sit amet risus nullam eget. Cursus turpis massa tincidunt dui ut ornare. Tempor id eu nisl nunc mi ipsum faucibus vitae aliquet.

					At erat pellentesque adipiscing commodo elit. Lorem donec massa sapien faucibus et molestie ac. Platea dictumst quisque sagittis purus sit amet volutpat. Turpis tincidunt id aliquet risus feugiat in ante. Mauris ultrices eros in cursus turpis. Urna nec tincidunt praesent semper feugiat nibh sed pulvinar proin. At quis risus sed vulputate odio ut enim. Lectus vestibulum mattis ullamcorper velit. Bibendum enim facilisis gravida neque convallis a. Pharetra vel turpis nunc eget lorem dolor. Elementum nibh tellus molestie nunc non blandit massa enim. Consequat semper viverra nam libero justo laoreet sit. Sem integer vitae justo eget magna. Consequat ac felis donec et odio. Porttitor rhoncus dolor purus non enim praesent elementum. Pulvinar etiam non quam lacus suspendisse faucibus interdum. Cras tincidunt lobortis feugiat vivamus at augue eget arcu dictum. Eu ultrices vitae auctor eu.

					Sed elementum tempus egestas sed sed risus. Sed risus pretium quam vulputate dignissim suspendisse. Nulla posuere sollicitudin aliquam ultrices. Risus commodo viverra maecenas accumsan lacus vel facilisis volutpat est. Nulla aliquet enim tortor at auctor urna nunc id cursus. Dolor purus non enim praesent elementum facilisis. Egestas pretium aenean pharetra magna ac placerat. Tristique senectus et netus et. Felis imperdiet proin fermentum leo vel. In hac habitasse platea dictumst vestibulum rhoncus. Vulputate ut pharetra sit amet aliquam id diam maecenas ultricies. Tempor orci dapibus ultrices in. Vel pretium lectus quam id leo in.

					Ultricies mi eget mauris pharetra et ultrices neque. Risus nec feugiat in fermentum posuere urna nec tincidunt. Vitae proin sagittis nisl rhoncus mattis. Quam viverra orci sagittis eu. Habitant morbi tristique senectus et netus et malesuada. Diam vel quam elementum pulvinar etiam non quam lacus suspendisse. Eu turpis egestas pretium aenean. Viverra nam libero justo laoreet sit amet cursus sit amet. Dignissim convallis aenean et tortor at risus viverra adipiscing at. Sit amet purus gravida quis blandit turpis cursus in hac. Sodales ut eu sem integer vitae justo. Tristique risus nec feugiat in. Rutrum tellus pellentesque eu tincidunt tortor.

					Consectetur purus ut faucibus pulvinar elementum integer enim neque. Ullamcorper a lacus vestibulum sed arcu non. Nec feugiat in fermentum posuere. Sit amet luctus venenatis lectus magna fringilla urna. Cursus euismod quis viverra nibh cras pulvinar. Fringilla ut morbi tincidunt augue interdum velit. Semper risus in hendrerit gravida rutrum. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt. In arcu cursus euismod quis. Vitae justo eget magna fermentum iaculis eu. Sit amet consectetur adipiscing elit ut aliquam purus. Aliquam malesuada bibendum arcu vitae. Semper feugiat nibh sed pulvinar proin. In iaculis nunc sed augue lacus.

					Scelerisque mauris pellentesque pulvinar pellentesque habitant morbi. Vulputate odio ut enim blandit. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet non. Urna id volutpat lacus laoreet non curabitur gravida arcu ac. Nunc id cursus metus aliquam eleifend mi. Luctus venenatis lectus magna fringilla urna porttitor rhoncus dolor. Malesuada fames ac turpis egestas maecenas pharetra convallis posuere. Nisl condimentum id venenatis a condimentum vitae. Adipiscing tristique risus nec feugiat in fermentum. Nunc sed blandit libero volutpat sed cras ornare arcu dui. Diam phasellus vestibulum lorem sed risus ultricies tristique nulla aliquet. Lectus magna fringilla urna porttitor rhoncus dolor purus non. Imperdiet massa tincidunt nunc pulvinar. Eu lobortis elementum nibh tellus molestie nunc non. Et ultrices neque ornare aenean euismod elementum nisi quis eleifend.

					Id consectetur purus ut faucibus pulvinar elementum. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada. Nunc id cursus metus aliquam eleifend mi in nulla. Leo vel fringilla est ullamcorper eget nulla facilisi etiam dignissim. Aliquam sem et tortor consequat. Quis imperdiet massa tincidunt nunc pulvinar sapien et ligula. Vestibulum lectus mauris ultrices eros. Donec pretium vulputate sapien nec sagittis aliquam malesuada. Proin sed libero enim sed. Ut pharetra sit amet aliquam id diam. In hendrerit gravida rutrum quisque non. Posuere lorem ipsum dolor sit amet consectetur adipiscing. Ac odio tempor orci dapibus ultrices in iaculis. Id leo in vitae turpis massa sed. Nisl nisi scelerisque eu ultrices vitae auctor. Cursus metus aliquam eleifend mi in nulla posuere. Elementum facilisis leo vel fringilla est. Enim nulla aliquet porttitor lacus luctus accumsan tortor. Curabitur vitae nunc sed velit dignissim sodales ut eu sem.

					Integer vitae justo eget magna fermentum iaculis. Phasellus faucibus scelerisque eleifend donec. In egestas erat imperdiet sed euismod nisi porta. Est sit amet facilisis magna. Adipiscing elit duis tristique sollicitudin nibh. Rhoncus aenean vel elit scelerisque mauris pellentesque. Vitae ultricies leo integer malesuada. Fermentum odio eu feugiat pretium nibh ipsum consequat. Mi quis hendrerit dolor magna eget est lorem ipsum. At consectetur lorem donec massa sapien faucibus et. Ullamcorper a lacus vestibulum sed arcu. Ultrices vitae auctor eu augue ut. At erat pellentesque adipiscing commodo elit at imperdiet. Accumsan lacus vel facilisis volutpat est velit egestas dui. Sit amet mauris commodo quis imperdiet massa tincidunt. Orci ac auctor augue mauris augue neque gravida in. Rhoncus aenean vel elit scelerisque mauris pellentesque. Metus aliquam eleifend mi in nulla posuere sollicitudin. In mollis nunc sed id semper. Posuere morbi leo urna molestie at elementum eu facilisis.

					Tellus molestie nunc non blandit massa enim nec dui. Ornare quam viverra orci sagittis eu volutpat odio. Enim tortor at auctor urna nunc id cursus metus aliquam. Tincidunt lobortis feugiat vivamus at augue eget arcu. Egestas diam in arcu cursus euismod quis. Turpis egestas sed tempus urna et pharetra pharetra massa massa. Cursus risus at ultrices mi. Urna porttitor rhoncus dolor purus non enim praesent elementum. Sed velit dignissim sodales ut eu sem integer. Nunc faucibus a pellentesque sit amet. Vitae tempus quam pellentesque nec nam aliquam sem. Ultrices eros in cursus turpis massa tincidunt. Aliquam etiam erat velit scelerisque in. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis. Tellus orci ac auctor augue mauris augue. Id volutpat lacus laoreet non curabitur gravida arcu. Nunc aliquet bibendum enim facilisis gravida. Nunc sed augue lacus viverra vitae congue eu consequat. In eu mi bibendum neque.

					Mi proin sed libero enim sed faucibus turpis. Id porta nibh venenatis cras sed felis eget velit. Ipsum dolor sit amet consectetur adipiscing elit pellentesque habitant morbi. Amet nulla facilisi morbi tempus. Ut lectus arcu bibendum at varius vel pharetra. Ut morbi tincidunt augue interdum velit euismod in pellentesque. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Integer enim neque volutpat ac tincidunt vitae. Sodales ut eu sem integer vitae justo. Sit amet venenatis urna cursus. Sed nisi lacus sed viverra. Pellentesque adipiscing commodo elit at imperdiet. Molestie nunc non blandit massa enim nec dui nunc.

					Arcu odio ut sem nulla pharetra diam sit. Sed odio morbi quis commodo odio. Pellentesque adipiscing commodo elit at imperdiet. Vitae justo eget magna fermentum iaculis eu. Aliquet bibendum enim facilisis gravida neque convallis a cras semper. Elementum nisi quis eleifend quam adipiscing vitae proin sagittis. Semper quis lectus nulla at volutpat. In pellentesque massa placerat duis. Dolor magna eget est lorem ipsum. Ut sem nulla pharetra diam sit. Rhoncus urna neque viverra justo nec ultrices dui. Quisque sagittis purus sit amet volutpat consequat mauris. Magna eget est lorem ipsum. Consequat mauris nunc congue nisi vitae suscipit. Duis convallis convallis tellus id interdum velit laoreet id donec. Ac tortor dignissim convallis aenean. Aliquet nibh praesent tristique magna sit amet purus.

					Maecenas ultricies mi eget mauris pharetra et ultrices neque. Sit amet nisl purus in mollis nunc sed. Pretium nibh ipsum consequat nisl vel pretium lectus. Sed libero enim sed faucibus turpis in eu mi bibendum. Sollicitudin ac orci phasellus egestas. Adipiscing bibendum est ultricies integer quis auctor elit sed vulputate. Duis at consectetur lorem donec massa sapien faucibus. Amet cursus sit amet dictum sit amet justo donec enim. Egestas congue quisque egestas diam in arcu cursus. Pulvinar pellentesque habitant morbi tristique senectus. In ornare quam viverra orci sagittis eu volutpat odio facilisis. Ultrices gravida dictum fusce ut placerat orci nulla pellentesque. Nunc sed velit dignissim sodales. Nulla porttitor massa id neque aliquam vestibulum morbi blandit. Nibh praesent tristique magna sit amet. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Fermentum iaculis eu non diam.

					Vulputate ut pharetra sit amet aliquam. Amet commodo nulla facilisi nullam vehicula. Diam ut venenatis tellus in metus. Id venenatis a condimentum vitae sapien pellentesque habitant. Vulputate dignissim suspendisse in est ante in nibh. Suspendisse faucibus interdum posuere lorem ipsum. Vel quam elementum pulvinar etiam non quam lacus suspendisse faucibus. Velit scelerisque in dictum non consectetur a erat. Imperdiet massa tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada. Ornare aenean euismod elementum nisi quis. Ipsum dolor sit amet consectetur adipiscing elit ut. Sed arcu non odio euismod lacinia at quis. Non nisi est sit amet facilisis magna etiam. Dictumst quisque sagittis purus sit amet volutpat consequat mauris. Ac auctor augue mauris augue. Urna nunc id cursus metus aliquam eleifend mi in. Aliquam vestibulum morbi blandit cursus risus at ultrices. Enim eu turpis egestas pretium aenean pharetra magna.

					Mattis vulputate enim nulla aliquet porttitor lacus luctus accumsan tortor. Nulla facilisi etiam dignissim diam quis enim lobortis. Et molestie ac feugiat sed. Facilisi nullam vehicula ipsum a arcu cursus. Neque convallis a cras semper auctor neque vitae tempus. Ultricies leo integer malesuada nunc vel risus commodo viverra maecenas. Facilisi nullam vehicula ipsum a arcu cursus vitae congue mauris. Enim diam vulputate ut pharetra sit amet aliquam id. Purus faucibus ornare suspendisse sed. Mi tempus imperdiet nulla malesuada pellentesque. Dapibus ultrices in iaculis nunc sed augue lacus. Arcu non odio euismod lacinia at quis. Amet cursus sit amet dictum sit amet justo. Habitasse platea dictumst quisque sagittis purus sit amet volutpat consequat. Sit amet est placerat in egestas erat imperdiet.

					Eget aliquet nibh praesent tristique magna sit amet purus. Egestas integer eget aliquet nibh. Dolor sit amet consectetur adipiscing elit pellentesque habitant morbi. Turpis massa sed elementum tempus egestas. Velit laoreet id donec ultrices tincidunt. Urna condimentum mattis pellentesque id nibh tortor id. Nulla malesuada pellentesque elit eget gravida cum sociis natoque. Dictum varius duis at consectetur lorem donec massa sapien. Nec feugiat nisl pretium fusce id velit ut tortor pretium. Id consectetur purus ut faucibus pulvinar elementum integer enim neque. Tortor dignissim convallis aenean et tortor at. Ac feugiat sed lectus vestibulum.

					Morbi tristique senectus et netus. Et odio pellentesque diam volutpat. Nec nam aliquam sem et. Tristique nulla aliquet enim tortor at auctor urna. Aliquet nec ullamcorper sit amet risus. Dui faucibus in ornare quam viverra orci sagittis eu. Velit laoreet id donec ultrices tincidunt. Sed risus ultricies tristique nulla aliquet enim tortor at auctor. Proin fermentum leo vel orci porta non pulvinar neque. Sed sed risus pretium quam vulputate dignissim suspendisse in est.

					Purus sit amet volutpat consequat mauris. Aliquet eget sit amet tellus cras adipiscing enim. Nunc sed blandit libero volutpat sed cras ornare arcu. Duis at consectetur lorem donec massa. Dolor sit amet consectetur adipiscing elit pellentesque habitant. Amet aliquam id diam maecenas ultricies mi eget. Faucibus purus in massa tempor nec feugiat. Nunc faucibus a pellentesque sit amet. Vitae auctor eu augue ut lectus arcu. Etiam dignissim diam quis enim lobortis scelerisque fermentum dui. A condimentum vitae sapien pellentesque habitant morbi tristique. Tellus integer feugiat scelerisque varius morbi enim. Ut aliquam purus sit amet luctus venenatis. Volutpat est velit egestas dui id ornare arcu odio. Libero justo laoreet sit amet cursus sit amet. Sed cras ornare arcu dui vivamus arcu felis. Massa sapien faucibus et molestie ac feugiat sed lectus. Semper viverra nam libero justo. Neque vitae tempus quam pellentesque nec nam aliquam.

					Neque viverra justo nec ultrices. Vitae suscipit tellus mauris a diam maecenas. Ornare aenean euismod elementum nisi quis eleifend. Ridiculus mus mauris vitae ultricies leo. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi. Duis tristique sollicitudin nibh sit amet commodo nulla facilisi nullam. Nibh tortor id aliquet lectus proin nibh nisl. Purus sit amet luctus venenatis lectus magna fringilla. Eget aliquet nibh praesent tristique magna. Viverra adipiscing at in tellus integer feugiat.

					Nisl nisi scelerisque eu ultrices. Aliquet nibh praesent tristique magna sit amet. Et netus et malesuada fames ac. Habitant morbi tristique senectus et netus et. Eu facilisis sed odio morbi quis commodo odio. Condimentum id venenatis a condimentum vitae sapien pellentesque habitant morbi. Ullamcorper eget nulla facilisi etiam dignissim diam quis. Semper risus in hendrerit gravida rutrum. Enim nulla aliquet porttitor lacus luctus. Sed libero enim sed faucibus turpis in eu mi bibendum. Varius sit amet mattis vulputate enim. Aenean sed adipiscing diam donec. Etiam sit amet nisl purus in mollis.

					Accumsan sit amet nulla facilisi morbi tempus. Tortor pretium viverra suspendisse potenti nullam ac. Quam quisque id diam vel. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et netus. Porttitor lacus luctus accumsan tortor posuere ac. Tortor id aliquet lectus proin. Ac tincidunt vitae semper quis. Leo urna molestie at elementum eu. Nibh cras pulvinar mattis nunc sed blandit libero volutpat. Diam maecenas ultricies mi eget mauris. In nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque. Id nibh tortor id aliquet lectus. Neque convallis a cras semper auctor neque vitae tempus quam. Tellus integer feugiat scelerisque varius morbi enim nunc faucibus a. Dapibus ultrices in iaculis nunc sed augue lacus viverra. Hendrerit dolor magna eget est lorem ipsum dolor. Enim facilisis gravida neque convallis a cras semper auctor neque. Tempus egestas sed sed risus pretium quam. Sit amet consectetur adipiscing elit ut aliquam purus sit amet.

					Viverra orci sagittis eu volutpat odio. Maecenas sed enim ut sem viverra aliquet. Dui vivamus arcu felis bibendum. Posuere urna nec tincidunt praesent. Scelerisque varius morbi enim nunc faucibus. Amet nisl purus in mollis nunc sed id semper. Egestas dui id ornare arcu odio. Euismod lacinia at quis risus sed vulputate odio. Quam lacus suspendisse faucibus interdum posuere lorem ipsum. Semper quis lectus nulla at volutpat diam ut venenatis. Enim nec dui nunc mattis enim ut tellus. Odio euismod lacinia at quis risus. Mi proin sed libero enim sed faucibus turpis. Lectus sit amet est placerat in egestas erat imperdiet sed. Odio aenean sed adipiscing diam donec adipiscing tristique. Amet aliquam id diam maecenas ultricies mi. In nulla posuere sollicitudin aliquam ultrices sagittis orci a.

					Fermentum odio eu feugiat pretium. Nunc faucibus a pellentesque sit amet porttitor. Tincidunt ornare massa eget egestas purus viverra accumsan in. Viverra tellus in hac habitasse. Mattis rhoncus urna neque viverra justo nec. Magna sit amet purus gravida quis blandit turpis cursus in. Id nibh tortor id aliquet lectus. Eros donec ac odio tempor orci dapibus ultrices in. Vel pharetra vel turpis nunc eget lorem dolor sed. Iaculis urna id volutpat lacus. Lobortis scelerisque fermentum dui faucibus in. Scelerisque mauris pellentesque pulvinar pellentesque habitant morbi. Aliquet nibh praesent tristique magna sit amet. Laoreet non curabitur gravida arcu ac tortor dignissim convallis. Ultrices sagittis orci a scelerisque. Et tortor consequat id porta nibh. Sit amet risus nullam eget felis. Lacus sed turpis tincidunt id aliquet risus feugiat.

					Egestas tellus rutrum tellus pellentesque eu tincidunt tortor aliquam. Nunc non blandit massa enim. Nunc congue nisi vitae suscipit tellus mauris a diam maecenas. Aliquet nibh praesent tristique magna sit amet purus gravida quis. Malesuada nunc vel risus commodo viverra maecenas accumsan lacus vel. Dui faucibus in ornare quam. Massa tincidunt dui ut ornare lectus sit amet est placerat. Eu scelerisque felis imperdiet proin. Nisi vitae suscipit tellus mauris a diam maecenas sed. Viverra nibh cras pulvinar mattis nunc sed blandit libero. Nisi vitae suscipit tellus mauris a. Quam nulla porttitor massa id neque aliquam vestibulum.

					Lectus arcu bibendum at varius vel pharetra vel turpis. Pretium nibh ipsum consequat nisl vel pretium. Amet mauris commodo quis imperdiet massa tincidunt nunc pulvinar. At risus viverra adipiscing at in tellus integer. Sed enim ut sem viverra aliquet. Ut lectus arcu bibendum at. Eget dolor morbi non arcu risus quis. Volutpat sed cras ornare arcu dui vivamus arcu felis. Eros donec ac odio tempor orci dapibus ultrices in. Et tortor consequat id porta nibh. Ultrices eros in cursus turpis massa. Malesuada fames ac turpis egestas integer eget. Condimentum vitae sapien pellentesque habitant. Nec dui nunc mattis enim ut tellus. Velit ut tortor pretium viverra suspendisse potenti nullam. Tincidunt nunc pulvinar sapien et ligula ullamcorper.

					Et sollicitudin ac orci phasellus egestas tellus rutrum. Sapien pellentesque habitant morbi tristique senectus et netus et. Ornare arcu odio ut sem. Enim neque volutpat ac tincidunt vitae semper quis. Volutpat diam ut venenatis tellus in metus vulputate. Vel fringilla est ullamcorper eget nulla. Tristique magna sit amet purus gravida quis blandit turpis. Quis blandit turpis cursus in hac habitasse. Aliquam faucibus purus in massa. Tellus orci ac auctor augue mauris augue. Mi sit amet mauris commodo quis imperdiet. Enim nec dui nunc mattis enim ut tellus elementum sagittis. Tincidunt nunc pulvinar sapien et. Curabitur gravida arcu ac tortor dignissim convallis aenean et tortor. Amet nisl purus in mollis nunc sed id semper risus. Egestas dui id ornare arcu odio ut sem. Interdum velit laoreet id donec ultrices tincidunt arcu non sodales. Viverra suspendisse potenti nullam ac tortor. Ut sem nulla pharetra diam sit amet nisl. Facilisi morbi tempus iaculis urna.

					Eu ultrices vitae auctor eu augue. Placerat orci nulla pellentesque dignissim enim sit. Amet cursus sit amet dictum sit amet. Tempor commodo ullamcorper a lacus vestibulum sed arcu non odio. Egestas quis ipsum suspendisse ultrices gravida dictum fusce ut placerat. Facilisis magna etiam tempor orci eu lobortis elementum nibh tellus. Sit amet venenatis urna cursus. Ut sem viverra aliquet eget sit amet. Ut lectus arcu bibendum at varius. Tortor at risus viverra adipiscing at in. Et molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit. In ornare quam viverra orci sagittis eu volutpat. Elit scelerisque mauris pellentesque pulvinar pellentesque. At tempor commodo ullamcorper a lacus vestibulum sed arcu non. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Facilisis leo vel fringilla est. Tellus cras adipiscing enim eu turpis.

					Maecenas volutpat blandit aliquam etiam erat velit scelerisque in dictum. Lacus viverra vitae congue eu consequat. Sodales ut eu sem integer. Malesuada fames ac turpis egestas integer eget aliquet nibh. Netus et malesuada fames ac turpis. Lectus quam id leo in. Proin libero nunc consequat interdum varius sit amet mattis vulputate. Tellus at urna condimentum mattis pellentesque. Nunc id cursus metus aliquam eleifend mi in. Cursus metus aliquam eleifend mi in. Et ligula ullamcorper malesuada proin libero. Blandit volutpat maecenas volutpat blandit aliquam etiam erat velit scelerisque. Nisl nunc mi ipsum faucibus vitae. Laoreet non curabitur gravida arcu ac tortor. At tellus at urna condimentum mattis. Velit ut tortor pretium viverra suspendisse potenti nullam ac. Mi in nulla posuere sollicitudin aliquam ultrices sagittis. Orci eu lobortis elementum nibh tellus molestie nunc. Turpis nunc eget lorem dolor sed viverra ipsum nunc aliquet. Ornare arcu dui vivamus arcu felis bibendum ut tristique et.

					Lacus vestibulum sed arcu non odio euismod lacinia. Consequat mauris nunc congue nisi vitae suscipit tellus mauris a. Accumsan sit amet nulla facilisi morbi tempus iaculis urna id. At tempor commodo ullamcorper a lacus. Duis ut diam quam nulla porttitor massa id neque. Egestas sed tempus urna et pharetra pharetra. Ut tristique et egestas quis ipsum. Diam vulputate ut pharetra sit amet aliquam id. Risus nullam eget felis eget nunc lobortis mattis. Quis risus sed vulputate odio ut enim blandit. Id donec ultrices tincidunt arcu non sodales neque. Quis ipsum suspendisse ultrices gravida. Lacus vestibulum sed arcu non. Duis convallis convallis tellus id interdum velit laoreet id donec. Fames ac turpis egestas maecenas. Elit ut aliquam purus sit amet. Neque sodales ut etiam sit amet nisl purus in. Sagittis id consectetur purus ut faucibus pulvinar elementum integer enim. Ultricies leo integer malesuada nunc.

					Ipsum suspendisse ultrices gravida dictum fusce ut placerat orci. Semper feugiat nibh sed pulvinar. Amet porttitor eget dolor morbi non arcu risus. Consectetur adipiscing elit duis tristique sollicitudin nibh sit amet commodo. Tellus orci ac auctor augue mauris augue neque. Facilisi etiam dignissim diam quis. Nisl purus in mollis nunc sed id semper risus. Id leo in vitae turpis massa. Enim nunc faucibus a pellentesque sit amet. Fringilla urna porttitor rhoncus dolor purus. Nulla facilisi morbi tempus iaculis urna. Quisque id diam vel quam elementum pulvinar etiam non quam. Tempor orci eu lobortis elementum nibh. Praesent elementum facilisis leo vel fringilla. Sed egestas egestas fringilla phasellus faucibus scelerisque eleifend donec. Mi tempus imperdiet nulla malesuada pellentesque elit. Gravida neque convallis a cras semper auctor neque vitae tempus.

					Ut sem nulla pharetra diam sit amet nisl suscipit adipiscing. Amet nisl suscipit adipiscing bibendum est ultricies integer. Quam lacus suspendisse faucibus interdum posuere lorem ipsum dolor. Sit amet volutpat consequat mauris nunc congue nisi. Lectus proin nibh nisl condimentum id. Viverra nibh cras pulvinar mattis nunc sed. Nunc mattis enim ut tellus elementum sagittis vitae et leo. Justo eget magna fermentum iaculis eu non diam phasellus vestibulum. Tellus cras adipiscing enim eu turpis egestas pretium. Tempor orci eu lobortis elementum nibh tellus. Vitae tempus quam pellentesque nec nam aliquam. Adipiscing elit duis tristique sollicitudin nibh sit amet commodo. Donec enim diam vulputate ut. Semper viverra nam libero justo laoreet sit amet. Semper quis lectus nulla at volutpat diam ut venenatis tellus. Tempor id eu nisl nunc mi. Enim nulla aliquet porttitor lacus. Volutpat est velit egestas dui id ornare. Pellentesque sit amet porttitor eget.
				</div>
				<div class="mt-10">
				<input type="checkbox" name="checked" id="checked">
				I have read and accept the terms and conditions
				</div>
			</div>
			
			<div class="submit">
				<button class="red-button">Submit</button>
			</div>
			</form>
			<!-- <a href="<?php echo base_url('index.php/welcome/check') ?>">Check</a> -->
		</div>
	</div>
</body>

</html>